### ISSUE TITLE
Error when using MagicCloud on view

### ISSUE THREAD

**Issue by Francklepanda** [zverok/magic_cloud#12]
Hello

when I try to use MagicCloud::Cloud.new(words, rotate: :free, scale: :log)
it shows me #<MagicCloud::Cloud:0x007fa033342a58> on my view

how can I use it ? will it create an image and I should use image_tag ? 
sorry for this question I think I didn't understand something ^^

Franck

**Comment by zverok** [comment]
MagicCloud is a standalone Ruby library, it knows nothing about Rails.
So, your typical workflow to show it in Rails view is:
1. Create cloud with `cloud = MagicCloud::Cloud.new(...)`
2. Draw it: `img = cloud.draw(width, height)`
3. Save it: `img.write('some_name.png')`
4. Use the created file in image tag: `image_tag 'some_name.png'`

Note, that it will produce static cloud image (which is the target of the library).
If you need a pretty JS word cloud, clickable and recizable, consider using d3.js and https://github.com/jasondavies/d3-cloud

**Comment by Francklepanda** [comment]
Thanks a lot !
I don't understand why I have some words who disappear :/ 

my code is : 
- words = [['Enfant',4],['Famille',5],['Meditation',6],['Motcle',5],['Patience',5],['Vertue',5]]
- cloud = MagicCloud::Cloud.new(words)
- img = cloud.draw(400, 300)
- img.write('some_name.png')

and the result : 
![some_name](https://user-images.githubusercontent.com/7558353/30007166-2281adee-9109-11e7-8aa5-1830970d1506.png)

Thanks for https://github.com/jasondavies/d3-cloud I think I will use that to have clickable words :)

**Comment by zverok** [comment]
> I don't understand why I have some words who disappear :/

Its because magic cloud is dumb (I didn't have enough time recently to update it): it calculates long words size with default font, sees it is too huge for the image size and just drops them. Try larger image size...
