### ISSUE TITLE
FloatDomainError (NaN) error if all words have same count or array contains only one word.

### ISSUE THREAD

**Issue by jasjeet30** [zverok/magic_cloud#21]
`words = [
  [Apple, 10], [Banana, 10]
]`
`cloud = MagicCloud::Cloud.new(words, rotate: :none, scale: :log)`
`img = cloud.draw(800, 600)`
`file_path = Rails.root.join("tmp", "#{id}.png")`
`img.write(file_path)`
`Error performing GenerateWordCloudJob (Job ID: 51ca485a-0dd0-4d75-90b5-30d896165f7b) from Async(default) in 1.1ms: FloatDomainError (NaN):`

**Comment by zverok** [comment]
Fixed by #22 and released as 0.0.5
