### ISSUE TITLE
Issue when not all words are drawn

### ISSUE THREAD

**Issue by mamantoha** [zverok/magic_cloud#5]
Hi!

First of all thank you for the great library! It was very helpful for me.

And I found an issue.

Example code:

```
require 'magic_cloud'

words = [['interesting', 61], ['good', 14], ['bad', 3], ['cool', 2], ['music', 2], ['films', 1], ['books', 1]]


cloud = MagicCloud::Cloud.new(words, rotate: :free, scale: :log)

img = cloud.draw(width = 200, height = 200)
img.write('issue.png')
```

This code gets me different results, but always without words `interesting` and `good`.

![issue](https://cloud.githubusercontent.com/assets/61285/15099150/ba568a20-1556-11e6-9a6d-b60704b076b5.png)

![issue](https://cloud.githubusercontent.com/assets/61285/15099152/c454d77a-1556-11e6-90e2-822ab0e8b687.png)

![issue](https://cloud.githubusercontent.com/assets/61285/15099155/ccf1c726-1556-11e6-8e05-2e952ce92942.png)

Can you look at this?

**Comment by mamantoha** [comment]
UPD. I found that problem with `width = 200, height = 200`.

It works fine with something like that `width = 1000, height = 1000`

![issue](https://cloud.githubusercontent.com/assets/61285/15099247/2a9aa5a8-1559-11e6-8dfb-b3f0444f9e51.png)

**Comment by zverok** [comment]
Yep, that's, unfortunately, part of the algo: if some word doesn't fit into current image size with current font size, it is just ignored silently. Many things like this one should be cleaned up, but I just can't have a time for this library currently :( I should do better.
